evaluation:
  retrieval:
    retrieval_eval_path: configs/evaluation/retrieval_eval.jsonl
    top_k: 5
    repeat_per_query: 1
    output_path: outputs/evaluation/retrieval_eval_result.json
    include_query_details: true

  rag:
    rag_eval_path: configs/evaluation/retrieval_eval.jsonl
    conditions:
      # - text_only
      # - image_only
      - text_image
    models:
      - label: qwen3_vl_plus
        model_name: qwen3-vl-plus
    repeat_per_query: 5
    output_path: outputs/evaluation/eval_rag_result.json
    include_query_details: true
